// Code generated by counterfeiter. DO NOT EDIT.
package usagefakes

import (
	"sync"
)

type FakeCredentialsGetter struct {
	GetCredentialsStub        func() ([]byte, []byte)
	getCredentialsMutex       sync.RWMutex
	getCredentialsArgsForCall []struct {
	}
	getCredentialsReturns struct {
		result1 []byte
		result2 []byte
	}
	getCredentialsReturnsOnCall map[int]struct {
		result1 []byte
		result2 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredentialsGetter) GetCredentials() ([]byte, []byte) {
	fake.getCredentialsMutex.Lock()
	ret, specificReturn := fake.getCredentialsReturnsOnCall[len(fake.getCredentialsArgsForCall)]
	fake.getCredentialsArgsForCall = append(fake.getCredentialsArgsForCall, struct {
	}{})
	stub := fake.GetCredentialsStub
	fakeReturns := fake.getCredentialsReturns
	fake.recordInvocation("GetCredentials", []interface{}{})
	fake.getCredentialsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredentialsGetter) GetCredentialsCallCount() int {
	fake.getCredentialsMutex.RLock()
	defer fake.getCredentialsMutex.RUnlock()
	return len(fake.getCredentialsArgsForCall)
}

func (fake *FakeCredentialsGetter) GetCredentialsCalls(stub func() ([]byte, []byte)) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = stub
}

func (fake *FakeCredentialsGetter) GetCredentialsReturns(result1 []byte, result2 []byte) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = nil
	fake.getCredentialsReturns = struct {
		result1 []byte
		result2 []byte
	}{result1, result2}
}

func (fake *FakeCredentialsGetter) GetCredentialsReturnsOnCall(i int, result1 []byte, result2 []byte) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = nil
	if fake.getCredentialsReturnsOnCall == nil {
		fake.getCredentialsReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 []byte
		})
	}
	fake.getCredentialsReturnsOnCall[i] = struct {
		result1 []byte
		result2 []byte
	}{result1, result2}
}

func (fake *FakeCredentialsGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getCredentialsMutex.RLock()
	defer fake.getCredentialsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredentialsGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
