%% mermaid source for advanced-routing.png diagram
graph LR
    users[Users]
    ngfSvc["Public Endpoint\nfor\ncafe.example.com"]
    subgraph cluster [Kubernetes Cluster]
        subgraph clusterPadding [" "]
            subgraph clusterPadding2 [" "]
                subgraph gwNS [Namespace\nnginx-gateway]
                    ngfPod[Pod\nnginx-gateway]
                end
            end
        end
        subgraph appNs [Namespace\ndefault]
            subgraph nsPadding [" "]
                coffeeV1Pod[Pod\ncoffee v1]
                coffeeV2Pod[Pod\ncoffee v2]
                teaPod[Pod\ntea]
                teaPostPod[Pod\ntea-post]
            end
        end
    end
  ngfSvc --> ngfPod
  ngfPod --/coffee--> coffeeV1Pod
  ngfPod --/coffee\nheader: version=v2\nOR\n/coffee?TEST=v2--> coffeeV2Pod
  ngfPod --GET /tea--> teaPod
  ngfPod --POST /tea--> teaPostPod
  users --> ngfSvc
  class clusterPadding,nsPadding,clusterPadding2 noBorder
  class gwNS,appNs namespace
  class ngfSvc,ngfPod nginxNode
  class coffeeV1Pod,coffeeV2Pod coffeeNode
  class teaPod,teaPostPod teaNode
  classDef noBorder stroke:none,fill:none
  classDef default fill:#FFFFFF,stroke:#000000
  classDef namespace fill:#FFFFFF,stroke:#036ffc,stroke-dasharray: 5 5,text-align:center
  classDef nginxNode fill:#b4e0ad,stroke:#2AA317
  classDef coffeeNode fill:#edbd8c,stroke:#D9822B
  classDef teaNode fill:#ff8f6a,stroke:#e5805f
