%% mermaid source for route-all-traffic-app.png diagram
graph TB
  subgraph cluster [Kubernetes Cluster]
    style cluster fill:#FFFFFF,stroke:#000000
    svc[Service\ncoffee]
    pod1[Pod\ncoffee]
    pod2[Pod\ncoffee]
  end

  svc --> pod1 & pod2

  class pod1,pod2,svc appNode
  classDef appNode fill:#edbd8c,stroke:#D9822B
