%% mermaid source for route-all-traffic-flow.png diagram
graph LR
  clients[Clients]
  ngfSvc["Public IP Address\nfor\ncafe.example.com"]

    subgraph cluster [Kubernetes Cluster]
        style cluster fill:#FFFFFF,stroke:#000000
        subgraph clusterPadding [" "]
            subgraph clusterPadding2 [" "]
                subgraph gwNS [Namespace\nnginx-gateway]
                    ngfPod[Pod\nnginx-gateway]
                end
            end
        end

        subgraph appNs [Namespace\ndefault]
            subgraph nsPadding [" "]
                coffeePod1[Pod\ncoffee]
                coffeePod2[Pod\ncoffee]
            end
        end
    end



  ngfSvc --> ngfPod
  ngfPod --> coffeePod1 & coffeePod2
  clients --> ngfSvc

  class clusterPadding,nsPadding,clusterPadding2 noBorder
  class gwNS,appNs namespace
  class ngfPod,ngfSvc nginxNode
  class coffeePod1,coffeePod2 coffeeNode
  class clients clientNode


  classDef noBorder stroke:none,fill:none
  classDef default fill:#FFFFFF,stroke:#000000
  classDef namespace fill:#FFFFFF,stroke:#036ffc,stroke-dasharray: 5 5,text-align:center
  classDef nginxNode fill:#b4e0ad,stroke:#2AA317
  classDef coffeeNode fill:#edbd8c,stroke:#D9822B
  classDef clientNode fill:#D3D3D3
