// Code generated by counterfeiter. DO NOT EDIT.
package statusfakes

import (
	"context"
	"sync"

	"github.com/nginxinc/nginx-kubernetes-gateway/internal/state"
	"github.com/nginxinc/nginx-kubernetes-gateway/internal/status"
)

type FakeUpdater struct {
	ProcessStatusUpdatesStub        func(context.Context, []state.StatusUpdate)
	processStatusUpdatesMutex       sync.RWMutex
	processStatusUpdatesArgsForCall []struct {
		arg1 context.Context
		arg2 []state.StatusUpdate
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUpdater) ProcessStatusUpdates(arg1 context.Context, arg2 []state.StatusUpdate) {
	var arg2Copy []state.StatusUpdate
	if arg2 != nil {
		arg2Copy = make([]state.StatusUpdate, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.processStatusUpdatesMutex.Lock()
	fake.processStatusUpdatesArgsForCall = append(fake.processStatusUpdatesArgsForCall, struct {
		arg1 context.Context
		arg2 []state.StatusUpdate
	}{arg1, arg2Copy})
	stub := fake.ProcessStatusUpdatesStub
	fake.recordInvocation("ProcessStatusUpdates", []interface{}{arg1, arg2Copy})
	fake.processStatusUpdatesMutex.Unlock()
	if stub != nil {
		fake.ProcessStatusUpdatesStub(arg1, arg2)
	}
}

func (fake *FakeUpdater) ProcessStatusUpdatesCallCount() int {
	fake.processStatusUpdatesMutex.RLock()
	defer fake.processStatusUpdatesMutex.RUnlock()
	return len(fake.processStatusUpdatesArgsForCall)
}

func (fake *FakeUpdater) ProcessStatusUpdatesCalls(stub func(context.Context, []state.StatusUpdate)) {
	fake.processStatusUpdatesMutex.Lock()
	defer fake.processStatusUpdatesMutex.Unlock()
	fake.ProcessStatusUpdatesStub = stub
}

func (fake *FakeUpdater) ProcessStatusUpdatesArgsForCall(i int) (context.Context, []state.StatusUpdate) {
	fake.processStatusUpdatesMutex.RLock()
	defer fake.processStatusUpdatesMutex.RUnlock()
	argsForCall := fake.processStatusUpdatesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.processStatusUpdatesMutex.RLock()
	defer fake.processStatusUpdatesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ status.Updater = new(FakeUpdater)
