collections_config:
  Pages:
    path: content
    output: true
    filter:
      base: strict
    parse_branch_index: true
    name:
    description: ''
    icon: article
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - content
      - visual
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      Index Page:
        path: .cloudcannon/schemas/index-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
          path: '[relative_base_path]/_index.md'
          extra_data:
          publish_to:
          _inputs:
          _select_data:
          _structures:
        new_preview_url:
      Docs Page:
        path: .cloudcannon/schemas/docs-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
          path: '[relative_base_path]/{title|slugify}.md.'
          extra_data:
          publish_to:
          _inputs:
          _select_data:
          _structures:
        new_preview_url:
    schema_key:
  How To:
    path: content/how-to
    output: true
    url:
    filter:
      base: strict
      include:
      exclude:
    parse_branch_index:
    name:
    description: ''
    icon: event_available
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      Index Page:
        path: .cloudcannon/schemas/index-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
      Docs Page:
        path: .cloudcannon/schemas/docs-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
    schema_key:
  Installation:
    path: content/installation
    output: true
    url:
    filter:
      base: strict
      include:
      exclude:
    parse_branch_index:
    name:
    description: ''
    icon: event_available
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      Index Page:
        path: .cloudcannon/schemas/index-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
      Docs Page:
        path: .cloudcannon/schemas/docs-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
    schema_key:
  Overview:
    path: content/overview
    output: true
    url:
    filter:
      base: strict
      include:
      exclude:
    parse_branch_index:
    name:
    description: ''
    icon: event_available
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      Index Page:
        path: .cloudcannon/schemas/index-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
      Docs Page:
        path: .cloudcannon/schemas/docs-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
    schema_key:
  Reference:
    path: content/reference
    output: true
    url:
    filter:
      base: strict
      include:
      exclude:
    parse_branch_index:
    name:
    description: ''
    icon: event_available
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      Index Page:
        path: .cloudcannon/schemas/index-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
      Docs Page:
        path: .cloudcannon/schemas/docs-page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: note_add
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
    schema_key:
  Includes:
    path: content/includes/installation
    output: true
    url:
    filter:
      base: strict
      include:
      exclude:
    parse_branch_index:
    name:
    description: This collection is not output to the live site.
    icon: event_available
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
collections_config_override: true
_enabled_editors:
  - content
_inputs:
  menu:
    type: disabled
    hidden: false
    cascade: true
  weight:
    type: number
    options:
      min: 100
      max:
      step: 100
      empty_type: 'null'
    cascade: true
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
      values:
        - development
        - configuration
      value_key:
    cascade: true
  tags:
    type: array
    hidden: true
    cascade: true
  doctypes:
    type: array
    hidden: true
    cascade: true
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    undo: true
  content:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    undo: true
    code: true
    blockquote: true
    bulletedlist: true
    numberedlist: true  
    embed: true
    format: p h1 h2 h3 h4 h5 h6
    table: true
    snippet: true
base_url: /
data_config: true
editor:
  default_path: /nginx-gateway-fabric/
timezone: Etc/UTC
commit_templates:
  - template_string: '{commit_type}: {message|trim} {breaking_change|if=breaking_change_message}'
    _inputs:
      commit_type:
        type: select
        options:
          allow_empty: true
          values:
            - feature
            - fix
            - refactor
            - update
        cascade: true
      breaking_change_message:
        type: text
        cascade: true
    extra_data:
      breaking_change: |-

        ⚠️ {breaking_change_message}
_snippets_imports:
  hugo:
    exclude:
      - hugo_youtube
      - hugo_twitter
      - hugo_vimeo
      - hugo_instagram
_snippets:
  relref_link:
    snippet: "\\[[[text]]\\]({{< relref [[link]]>}})"
    params:
      text:
        parser: content
        options:
          editor_key: link_text
          raw: true
          forbidden_tokens:
            - "]"
      link:
        parser: argument
        options:
          model:
            editor_key: link_destination
          format:
            string_boundary:
              - '"'
              - "'"
    preview:
      view: "inline"
      text:
        - template: "RelRef Link: {link_text} → {link_destination}"
        - RelRef Link
      icon: dataset_linked
  important:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Important
      subtext:
        - key: content_markdown
        - Important note in a callout box.
      icon: priority_high
    definitions:
      shortcode_name: important
      content_key: content_markdown
      named_args: []
  note:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Note
      subtext:
        - key: content_markdown
        - Note in callout box.
      icon: edit_note
    definitions:
      shortcode_name: note
      content_key: content_markdown
      named_args: []
    _inputs:
      content_markdown:
        type: markdown
        options:
          allow_resize: true
          allow_custom_markup: false
          remove_custom_markup: false
          initial_height: 320
          blockquote: true
          bold: true
          bulletedlist: true
          code: true
          embed: true
          format: p h1 h2 h3 h4 h5 h6
          horizontalrule: true
          image: true
          image_size_attributes: true
          italic: true
          numberedlist: true
          redo: true
          snippet: true
          table: true
          underline: true
          undo: true
        cascade: true
  see-also:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: See also
      subtext:
        - key: content_markdown
        - See Also note in callout box.
      icon: visibility
    definitions:
      shortcode_name: see-also
      content_key: content_markdown
      named_args: []
  before-you-begin:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Befor You Begin
      subtext:
        - key: content_markdown
        - Before You Begin note in callout box.
      icon: front_hand
    definitions:
      shortcode_name: before-you-begin
      content_key: content_markdown
      named_args: []
  deprecated:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Deprecated
      subtext:
        - key: content_markdown
        - Deprecated callout in a box.
      icon: delete
    definitions:
      shortcode_name: deprecated
      content_key: content_markdown
      named_args: []
  caution:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Caution
      subtext:
        - key: content_markdown
        - Caution callout in a box.
      icon: announcement
    definitions:
      shortcode_name: caution
      content_key: content_markdown
      named_args: []
  warning:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Warning
      subtext:
        - key: content_markdown
        - Warning callout in a box.
      icon: warning
    definitions:
      shortcode_name: warning
      content_key: content_markdown
      named_args: []
  call-out:
    template: hugo_paired_shortcode_positional_args
    inline: false
    preview:
      text:
        - key: callout_title
        - Callout
      subtext:
        - key: content_markdown
        - Custome callout with title in a box.
      icon:
        - key: icon_param
        - document
    definitions:
      shortcode_name: call-out
      content_key: content_markdown
      positional_args:
        - editor_key: icon_param
          type: string
        - editor_key: callout_title
          type: string
  Internal comment:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Comment (Internal only)
      subtext:
        - key: content_markdown
        - Internal comment that will not be rendered in the page.
      icon: tag
    definitions:
      shortcode_name: comment
      content_key: content_markdown
      named_args: []
  include:
    template: hugo_shortcode_positional_args
    inline: true
    preview:
      text: Include
      subtext:
        - key: url
        - Include snippet.
      icon: file_copy
    definitions:
      shortcode_name: include
      positional_args:
        - editor_key: url
          type: string
  bootstrap-table:
    template: hugo_paired_shortcode_positional_args
    inline: false
    preview:
      text: Bootstrap Table
      subtext:
        - key: content_markdown_table
        - type: code
        - Markdown table using Bootstrap.
      icon: table_chart
    definitions:
      shortcode_name: bootstrap-table
      content_key: content_markdown_table
      positional_args:
        - editor_key: table_style
    _inputs:
      content_markdown_table:
        type: code
        cascade: true
  raw-html:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text: Raw HTML
      subtext:
        - key: content_code_block
        - Raw HTML Code.
      icon: html
    definitions:
      shortcode_name: raw-html
      content_key: content_code_block
      named_args: []
  img:
    template: hugo_shortcode_named_args
    inline: true
    preview:
      text:
        - key: src
        - Image
      subtext:
        - key: alt
        - Alternative text
      icon: image
    definitions:
      shortcode_name: img
      named_args:
        - editor_key: src
          type: string
        - editor_key: caption
          optional: true
          type: string
        - editor_key: alt
          optional: true
          type: string
        - editor_key: width
          optional: true
          type: string
        - editor_key: height
          optional: true
          type: string
  tab group:
    template: hugo_paired_shortcode_named_args
    inline: false
    preview:
      text:
        - key: name
        - Tab group section
      subtext:
        - key: content_code_block
        - Tabs content
      icon: tab
    definitions:
      shortcode_name: tabs
      content_key: content_code_block
      named_args:
        - editor_key: name
          type: string
  tab section:
    template: hugo_paired_markdown_shortcode_named_args
    inline: false
    preview:
      text:
        - key: name
        - Tab inside tabbed section
      subtext:
        - key: tab_content
        - Tab content
      icon: tab
    definitions:
      shortcode_name: tabs
      content_key: tab_content
      named_args:
        - editor_key: name
          type: string
  beta-badge:
    template: hugo_shortcode_positional_args
    inline: false
    preview:
      text: This topic documents an early access feature.
      subtext: >-
        These features are provided for you to try before they are generally
        available. You shouldn't use early access features for production
        purposes.
      icon: science
    definitions:
      shortcode_name: beta-badge
  relref:
    template: hugo_shortcode_positional_args
    inline: true
    preview:
      view: inline
      icon: link
      text:
        - key: url
        - Empty URL
    definitions:
      shortcode_name: relref
      positional_args:
        - editor_key: url
          type: string
  link:
    template: hugo_shortcode_positional_args
    inline: true
    preview:
      text:
        - key: text
        - Link to download a file
      icon: system_update_alt
    definitions:
      shortcode_name: link
      positional_args:
        - editor_key: url
          type: string
        - editor_key: text
  fontawesome-Icon:
    template: hugo_shortcode_positional_args
    inline: true
    preview:
      view: inline
      text: FA-icon
      icon:
        - key: icon_name
    definitions:
      shortcode_name: fa
      positional_args:
        - editor_key: icon_name
          type: string
        - editor_key: styles
          type: string
          optional: true
          remove_empty: true
  icon-resolved:
    template: hugo_markdown_shortcode_named_args
    inline: true
    preview:
      text: Resolved Bug Icon
      icon: bug_report
    definitions:
      shortcode_name: icon-resolved
      content_key: content_markdown
      named_args: []
  icon-bug:
    template: hugo_markdown_shortcode_named_args
    inline: true
    preview:
      text: Bug Icon
      icon: bug_report
    definitions:
      shortcode_name: icon-bug
      content_key: content_markdown
      named_args: []
  shortversions:
    template: hugo_shortcode_positional_args
    inline: false
    preview:
      text: Shortversions - This shortcode has been deprecated
      icon: format_list_numbered
    definitions:
      shortcode_name: shortversions
      positional_args:
        - editor_key: from
          type: string
        - editor_key: to
          type: string
        - editor_key: product
          type: string
  versions:
    template: hugo_shortcode_positional_args
    inline: false
    preview:
      text: Versions - This shortcode has been deprecated
      icon: format_list_numbered
    definitions:
      shortcode_name: versions
      positional_args:
        - editor_key: from
          type: string
        - editor_key: to
          type: string
        - editor_key: product
          type: string
  custom-styles:
    template: hugo_shortcode
    inline: false
    preview:
      text: Custom Styles
      icon: text_format
    definitions:
      shortcode_name: custom-styles
