%% mermaid source for route-all-traffic-flow.png diagram
graph LR
  clients[Clients]
  nkgSvc["Public IP Address\nhttp://cafe.example.com/"]

    subgraph cluster [Kubernetes Cluster]
        style cluster fill:#FFFFFF,stroke:#000000
        subgraph clusterPadding [" "]
            subgraph clusterPadding2 [" "]
                subgraph gwNS [Namespace\nnginx-gateway]
                    nkgPod[Pod\nnginx-gateway]
                end
            end
        end

        subgraph appNs [Namespace\ndefault]
            subgraph nsPadding [" "]
                coffeePod1[Pod\ncoffee]
                coffeePod2[Pod\ncoffee]
            end
        end
    end



  nkgSvc --> nkgPod
  nkgPod --> coffeePod1 & coffeePod2
  clients --> nkgSvc

  class clusterPadding,nsPadding,clusterPadding2 noBorder
  class gwNS,appNs namespace
  class nkgPod,nkgSvc nginxNode
  class coffeePod1,coffeePod2 coffeeNode
  class clients clientNode


  classDef noBorder stroke:none,fill:none
  classDef default fill:#FFFFFF,stroke:#000000
  classDef namespace fill:#FFFFFF,stroke:#036ffc,stroke-dasharray: 5 5,text-align:center
  classDef nginxNode fill:#b4e0ad,stroke:#2AA317
  classDef coffeeNode fill:#edbd8c,stroke:#D9822B
  classDef clientNode fill:#D3D3D3
