%% mermaid source for route-all-traffic-config.png diagram
graph LR
    subgraph config [Namespace default]
      subgraph padding [" "]
          direction LR
          style config fill:#FFFFFF,stroke:#000000
          subgraph gw[Gateway cafe]
              subgraph gwPadding [" "]
                  gwContents[HTTP/80]
              end
          end
          subgraph hr[HTTPRoute coffee]
              subgraph hrPadding [" "]
                  hrContents[cafe.example.com]
                  subgraph describeMatchAll [Match all\ntraffic]
                      subgraph describeMatchPadding [" "]
                          matchAll[Host: *\nPath: *]
                      end
                  end
                  subgraph describeService [Group matching\npods within a Service]
                      subgraph describePadding [" "]
                          coffeeSvc[Service\ncoffee]
                      end
                  end
              end
          end
      end
    end

  gwContents --> hrContents --> matchAll --> coffeeSvc
  class padding,gwPadding,hrPadding,describeMatchAll,describeService,describePadding,describeMatchPadding noBorder
  class gw gateway
  class hr httpRoute
  class matchAll,hrContents,coffeeSvc appDevNode
  class gwContents clusterOppNode

  classDef noBorder stroke:none,fill:none,text-align:center
  classDef default fill:#FFFFFF,stroke:#000000
  classDef gateway fill:#FFFFFF,stroke:#2AA317,stroke-dasharray: 3 3,text-align:center
  classDef httpRoute fill:#FFFFFF,stroke:#D9822B,stroke-dasharray: 3 3,text-align:center
  classDef appDevNode fill:#edbd8c,stroke:#D9822B
  classDef clusterOppNode fill:#b4e0ad,stroke:#2AA317
