// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nginxinc/nginx-gateway-kubernetes/pkg/apis/gateway/v1alpha1"
	"github.com/nginxinc/nginx-gateway-kubernetes/pkg/client/gateway/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type GatewayV1alpha1Interface interface {
	RESTClient() rest.Interface
	GatewayConfigsGetter
}

// GatewayV1alpha1Client is used to interact with features provided by the gateway.nginx.org group.
type GatewayV1alpha1Client struct {
	restClient rest.Interface
}

func (c *GatewayV1alpha1Client) GatewayConfigs() GatewayConfigInterface {
	return newGatewayConfigs(c)
}

// NewForConfig creates a new GatewayV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*GatewayV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &GatewayV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new GatewayV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *GatewayV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new GatewayV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *GatewayV1alpha1Client {
	return &GatewayV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *GatewayV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
