#!/bin/bash

mv site/public site/nginx-gateway-fabric
mkdir -p site/public
mv site/nginx-gateway-fabric site/public
mv site/public/nginx-gateway-fabric/_cloudcannon site/public

## Find and fix broken images and links caused by how the baseURL is set in the config.yml
find site/public -type f -name "*.html" -exec sed -i 's/="\/\//="\//g' {} \;