// Code generated by counterfeiter. DO NOT EDIT.
package secretsfakes

import (
	"sync"

	"github.com/nginxinc/nginx-kubernetes-gateway/internal/state/secrets"
	"k8s.io/apimachinery/pkg/types"
)

type FakeRequestManager struct {
	GetAndResetRequestedSecretsStub        func() []secrets.File
	getAndResetRequestedSecretsMutex       sync.RWMutex
	getAndResetRequestedSecretsArgsForCall []struct {
	}
	getAndResetRequestedSecretsReturns struct {
		result1 []secrets.File
	}
	getAndResetRequestedSecretsReturnsOnCall map[int]struct {
		result1 []secrets.File
	}
	RequestStub        func(types.NamespacedName) (string, error)
	requestMutex       sync.RWMutex
	requestArgsForCall []struct {
		arg1 types.NamespacedName
	}
	requestReturns struct {
		result1 string
		result2 error
	}
	requestReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRequestManager) GetAndResetRequestedSecrets() []secrets.File {
	fake.getAndResetRequestedSecretsMutex.Lock()
	ret, specificReturn := fake.getAndResetRequestedSecretsReturnsOnCall[len(fake.getAndResetRequestedSecretsArgsForCall)]
	fake.getAndResetRequestedSecretsArgsForCall = append(fake.getAndResetRequestedSecretsArgsForCall, struct {
	}{})
	stub := fake.GetAndResetRequestedSecretsStub
	fakeReturns := fake.getAndResetRequestedSecretsReturns
	fake.recordInvocation("GetAndResetRequestedSecrets", []interface{}{})
	fake.getAndResetRequestedSecretsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRequestManager) GetAndResetRequestedSecretsCallCount() int {
	fake.getAndResetRequestedSecretsMutex.RLock()
	defer fake.getAndResetRequestedSecretsMutex.RUnlock()
	return len(fake.getAndResetRequestedSecretsArgsForCall)
}

func (fake *FakeRequestManager) GetAndResetRequestedSecretsCalls(stub func() []secrets.File) {
	fake.getAndResetRequestedSecretsMutex.Lock()
	defer fake.getAndResetRequestedSecretsMutex.Unlock()
	fake.GetAndResetRequestedSecretsStub = stub
}

func (fake *FakeRequestManager) GetAndResetRequestedSecretsReturns(result1 []secrets.File) {
	fake.getAndResetRequestedSecretsMutex.Lock()
	defer fake.getAndResetRequestedSecretsMutex.Unlock()
	fake.GetAndResetRequestedSecretsStub = nil
	fake.getAndResetRequestedSecretsReturns = struct {
		result1 []secrets.File
	}{result1}
}

func (fake *FakeRequestManager) GetAndResetRequestedSecretsReturnsOnCall(i int, result1 []secrets.File) {
	fake.getAndResetRequestedSecretsMutex.Lock()
	defer fake.getAndResetRequestedSecretsMutex.Unlock()
	fake.GetAndResetRequestedSecretsStub = nil
	if fake.getAndResetRequestedSecretsReturnsOnCall == nil {
		fake.getAndResetRequestedSecretsReturnsOnCall = make(map[int]struct {
			result1 []secrets.File
		})
	}
	fake.getAndResetRequestedSecretsReturnsOnCall[i] = struct {
		result1 []secrets.File
	}{result1}
}

func (fake *FakeRequestManager) Request(arg1 types.NamespacedName) (string, error) {
	fake.requestMutex.Lock()
	ret, specificReturn := fake.requestReturnsOnCall[len(fake.requestArgsForCall)]
	fake.requestArgsForCall = append(fake.requestArgsForCall, struct {
		arg1 types.NamespacedName
	}{arg1})
	stub := fake.RequestStub
	fakeReturns := fake.requestReturns
	fake.recordInvocation("Request", []interface{}{arg1})
	fake.requestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRequestManager) RequestCallCount() int {
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	return len(fake.requestArgsForCall)
}

func (fake *FakeRequestManager) RequestCalls(stub func(types.NamespacedName) (string, error)) {
	fake.requestMutex.Lock()
	defer fake.requestMutex.Unlock()
	fake.RequestStub = stub
}

func (fake *FakeRequestManager) RequestArgsForCall(i int) types.NamespacedName {
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	argsForCall := fake.requestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRequestManager) RequestReturns(result1 string, result2 error) {
	fake.requestMutex.Lock()
	defer fake.requestMutex.Unlock()
	fake.RequestStub = nil
	fake.requestReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestManager) RequestReturnsOnCall(i int, result1 string, result2 error) {
	fake.requestMutex.Lock()
	defer fake.requestMutex.Unlock()
	fake.RequestStub = nil
	if fake.requestReturnsOnCall == nil {
		fake.requestReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.requestReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAndResetRequestedSecretsMutex.RLock()
	defer fake.getAndResetRequestedSecretsMutex.RUnlock()
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRequestManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ secrets.RequestManager = new(FakeRequestManager)
