// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	gatewayv1alpha1 "github.com/nginxinc/nginx-kubernetes-gateway/pkg/apis/gateway/v1alpha1"
	versioned "github.com/nginxinc/nginx-kubernetes-gateway/pkg/client/gateway/clientset/versioned"
	internalinterfaces "github.com/nginxinc/nginx-kubernetes-gateway/pkg/client/gateway/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nginxinc/nginx-kubernetes-gateway/pkg/client/gateway/listers/gateway/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GatewayConfigInformer provides access to a shared informer and lister for
// GatewayConfigs.
type GatewayConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GatewayConfigLister
}

type gatewayConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewGatewayConfigInformer constructs a new informer for GatewayConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGatewayConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGatewayConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredGatewayConfigInformer constructs a new informer for GatewayConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGatewayConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha1().GatewayConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha1().GatewayConfigs().Watch(context.TODO(), options)
			},
		},
		&gatewayv1alpha1.GatewayConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *gatewayConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGatewayConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gatewayConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gatewayv1alpha1.GatewayConfig{}, f.defaultInformer)
}

func (f *gatewayConfigInformer) Lister() v1alpha1.GatewayConfigLister {
	return v1alpha1.NewGatewayConfigLister(f.Informer().GetIndexer())
}
