// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/nginxinc/nginx-gateway-kubernetes/pkg/client/gateway/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GatewayConfigs returns a GatewayConfigInformer.
	GatewayConfigs() GatewayConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GatewayConfigs returns a GatewayConfigInformer.
func (v *version) GatewayConfigs() GatewayConfigInformer {
	return &gatewayConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
