title = "NGINX Gateway Fabric"
enableGitInfo = true
baseURL = "/"
staticDir = ["static"]
languageCode = "en-us"
description = "NGINX Gateway Fabric."
refLinksErrorLevel = "ERROR"
enableRobotsTXT = "true"
#canonifyURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsUseClasses = true

[caches]
  [caches.modules]
    maxAge = -1

[module]
[[module.imports]]
  path="github.com/nginxinc/nginx-hugo-theme"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "gitlab"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
  useSectionPageLists = "false"
  buildtype = "webdocs"
  RSSLink = "/index.xml"
  author = "NGINX Inc." # add your company name
  github = "nginxinc" # add your github profile name
  twitter = "@nginx" # add your twitter profile
  #email = ""
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]
  logo = "NGINX-product-icon.svg"

sectionPagesMenu = "docs"

ignoreFiles = [ "\\.sh$", "\\.DS_Store$", "\\.git.*$", "\\.txt$", "\\/config\\/.*", "README\\.*"]
