// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GatewayConfigListerExpansion allows custom methods to be added to
// GatewayConfigLister.
type GatewayConfigListerExpansion interface{}
