// Code generated by counterfeiter. DO NOT EDIT.
package telemetryfakes

import (
	"sync"

	"github.com/nginxinc/nginx-gateway-fabric/internal/mode/static/telemetry"
)

type FakeHealthChecker struct {
	GetReadyIfClosedChannelStub        func() <-chan struct{}
	getReadyIfClosedChannelMutex       sync.RWMutex
	getReadyIfClosedChannelArgsForCall []struct {
	}
	getReadyIfClosedChannelReturns struct {
		result1 <-chan struct{}
	}
	getReadyIfClosedChannelReturnsOnCall map[int]struct {
		result1 <-chan struct{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHealthChecker) GetReadyIfClosedChannel() <-chan struct{} {
	fake.getReadyIfClosedChannelMutex.Lock()
	ret, specificReturn := fake.getReadyIfClosedChannelReturnsOnCall[len(fake.getReadyIfClosedChannelArgsForCall)]
	fake.getReadyIfClosedChannelArgsForCall = append(fake.getReadyIfClosedChannelArgsForCall, struct {
	}{})
	stub := fake.GetReadyIfClosedChannelStub
	fakeReturns := fake.getReadyIfClosedChannelReturns
	fake.recordInvocation("GetReadyIfClosedChannel", []interface{}{})
	fake.getReadyIfClosedChannelMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHealthChecker) GetReadyIfClosedChannelCallCount() int {
	fake.getReadyIfClosedChannelMutex.RLock()
	defer fake.getReadyIfClosedChannelMutex.RUnlock()
	return len(fake.getReadyIfClosedChannelArgsForCall)
}

func (fake *FakeHealthChecker) GetReadyIfClosedChannelCalls(stub func() <-chan struct{}) {
	fake.getReadyIfClosedChannelMutex.Lock()
	defer fake.getReadyIfClosedChannelMutex.Unlock()
	fake.GetReadyIfClosedChannelStub = stub
}

func (fake *FakeHealthChecker) GetReadyIfClosedChannelReturns(result1 <-chan struct{}) {
	fake.getReadyIfClosedChannelMutex.Lock()
	defer fake.getReadyIfClosedChannelMutex.Unlock()
	fake.GetReadyIfClosedChannelStub = nil
	fake.getReadyIfClosedChannelReturns = struct {
		result1 <-chan struct{}
	}{result1}
}

func (fake *FakeHealthChecker) GetReadyIfClosedChannelReturnsOnCall(i int, result1 <-chan struct{}) {
	fake.getReadyIfClosedChannelMutex.Lock()
	defer fake.getReadyIfClosedChannelMutex.Unlock()
	fake.GetReadyIfClosedChannelStub = nil
	if fake.getReadyIfClosedChannelReturnsOnCall == nil {
		fake.getReadyIfClosedChannelReturnsOnCall = make(map[int]struct {
			result1 <-chan struct{}
		})
	}
	fake.getReadyIfClosedChannelReturnsOnCall[i] = struct {
		result1 <-chan struct{}
	}{result1}
}

func (fake *FakeHealthChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getReadyIfClosedChannelMutex.RLock()
	defer fake.getReadyIfClosedChannelMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHealthChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ telemetry.HealthChecker = new(FakeHealthChecker)
